/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SelectContextRouteImport } from './routes/select-context'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SuperAdminLeadsRouteImport } from './routes/super-admin.leads'
import { Route as SuperAdminAuditRouteImport } from './routes/super-admin.audit'
import { Route as AppTrialBalanceRouteImport } from './routes/app.trial-balance'
import { Route as AppTeepRouteImport } from './routes/app.teep'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPricingRouteImport } from './routes/app.pricing'
import { Route as AppMastersRouteImport } from './routes/app.masters'
import { Route as AppLedgerRouteImport } from './routes/app.ledger'
import { Route as AppEntryRouteImport } from './routes/app.entry'
import { Route as AppCashbookRouteImport } from './routes/app.cashbook'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppStockIndexRouteImport } from './routes/app.stock.index'
import { Route as AppStockSaleRouteImport } from './routes/app.stock.sale'
import { Route as AppMastersPartiesRouteImport } from './routes/app.masters.parties'
import { Route as AppMastersItemsRouteImport } from './routes/app.masters.items'
import { Route as AppMastersExpensesRouteImport } from './routes/app.masters.expenses'
import { Route as AppMastersCompaniesRouteImport } from './routes/app.masters.companies'
import { Route as AppEntryVoucherRouteImport } from './routes/app.entry.voucher'
import { Route as AppEntryChallanRouteImport } from './routes/app.entry.challan'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectContextRoute = SelectContextRouteImport.update({
  id: '/select-context',
  path: '/select-context',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SuperAdminLeadsRoute = SuperAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAuditRoute = SuperAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperAdminRoute,
} as any)
const AppTrialBalanceRoute = AppTrialBalanceRouteImport.update({
  id: '/trial-balance',
  path: '/trial-balance',
  getParentRoute: () => AppRoute,
} as any)
const AppTeepRoute = AppTeepRouteImport.update({
  id: '/teep',
  path: '/teep',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppEntryRoute = AppEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => AppRoute,
} as any)
const AppCashbookRoute = AppCashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppStockIndexRoute = AppStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AppRoute,
} as any)
const AppStockSaleRoute = AppStockSaleRouteImport.update({
  id: '/stock/sale',
  path: '/stock/sale',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersPartiesRoute = AppMastersPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppMastersItemsRoute = AppMastersItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppMastersExpensesRoute = AppMastersExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppMastersCompaniesRoute = AppMastersCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppEntryVoucherRoute = AppEntryVoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => AppEntryRoute,
} as any)
const AppEntryChallanRoute = AppEntryChallanRouteImport.update({
  id: '/challan',
  path: '/challan',
  getParentRoute: () => AppEntryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/select-context': typeof SelectContextRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/app/bills': typeof AppBillsRoute
  '/app/cashbook': typeof AppCashbookRoute
  '/app/entry': typeof AppEntryRouteWithChildren
  '/app/ledger': typeof AppLedgerRoute
  '/app/masters': typeof AppMastersRouteWithChildren
  '/app/pricing': typeof AppPricingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/teep': typeof AppTeepRoute
  '/app/trial-balance': typeof AppTrialBalanceRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/leads': typeof SuperAdminLeadsRoute
  '/app/': typeof AppIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/app/entry/challan': typeof AppEntryChallanRoute
  '/app/entry/voucher': typeof AppEntryVoucherRoute
  '/app/masters/companies': typeof AppMastersCompaniesRoute
  '/app/masters/expenses': typeof AppMastersExpensesRoute
  '/app/masters/items': typeof AppMastersItemsRoute
  '/app/masters/parties': typeof AppMastersPartiesRoute
  '/app/stock/sale': typeof AppStockSaleRoute
  '/app/stock/': typeof AppStockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/select-context': typeof SelectContextRoute
  '/app/bills': typeof AppBillsRoute
  '/app/cashbook': typeof AppCashbookRoute
  '/app/entry': typeof AppEntryRouteWithChildren
  '/app/ledger': typeof AppLedgerRoute
  '/app/masters': typeof AppMastersRouteWithChildren
  '/app/pricing': typeof AppPricingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/teep': typeof AppTeepRoute
  '/app/trial-balance': typeof AppTrialBalanceRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/leads': typeof SuperAdminLeadsRoute
  '/app': typeof AppIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/app/entry/challan': typeof AppEntryChallanRoute
  '/app/entry/voucher': typeof AppEntryVoucherRoute
  '/app/masters/companies': typeof AppMastersCompaniesRoute
  '/app/masters/expenses': typeof AppMastersExpensesRoute
  '/app/masters/items': typeof AppMastersItemsRoute
  '/app/masters/parties': typeof AppMastersPartiesRoute
  '/app/stock/sale': typeof AppStockSaleRoute
  '/app/stock': typeof AppStockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/select-context': typeof SelectContextRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/app/bills': typeof AppBillsRoute
  '/app/cashbook': typeof AppCashbookRoute
  '/app/entry': typeof AppEntryRouteWithChildren
  '/app/ledger': typeof AppLedgerRoute
  '/app/masters': typeof AppMastersRouteWithChildren
  '/app/pricing': typeof AppPricingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/teep': typeof AppTeepRoute
  '/app/trial-balance': typeof AppTrialBalanceRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/leads': typeof SuperAdminLeadsRoute
  '/app/': typeof AppIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/app/entry/challan': typeof AppEntryChallanRoute
  '/app/entry/voucher': typeof AppEntryVoucherRoute
  '/app/masters/companies': typeof AppMastersCompaniesRoute
  '/app/masters/expenses': typeof AppMastersExpensesRoute
  '/app/masters/items': typeof AppMastersItemsRoute
  '/app/masters/parties': typeof AppMastersPartiesRoute
  '/app/stock/sale': typeof AppStockSaleRoute
  '/app/stock/': typeof AppStockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/login'
    | '/select-context'
    | '/super-admin'
    | '/app/bills'
    | '/app/cashbook'
    | '/app/entry'
    | '/app/ledger'
    | '/app/masters'
    | '/app/pricing'
    | '/app/reports'
    | '/app/settings'
    | '/app/teep'
    | '/app/trial-balance'
    | '/super-admin/audit'
    | '/super-admin/leads'
    | '/app/'
    | '/super-admin/'
    | '/app/entry/challan'
    | '/app/entry/voucher'
    | '/app/masters/companies'
    | '/app/masters/expenses'
    | '/app/masters/items'
    | '/app/masters/parties'
    | '/app/stock/sale'
    | '/app/stock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/select-context'
    | '/app/bills'
    | '/app/cashbook'
    | '/app/entry'
    | '/app/ledger'
    | '/app/masters'
    | '/app/pricing'
    | '/app/reports'
    | '/app/settings'
    | '/app/teep'
    | '/app/trial-balance'
    | '/super-admin/audit'
    | '/super-admin/leads'
    | '/app'
    | '/super-admin'
    | '/app/entry/challan'
    | '/app/entry/voucher'
    | '/app/masters/companies'
    | '/app/masters/expenses'
    | '/app/masters/items'
    | '/app/masters/parties'
    | '/app/stock/sale'
    | '/app/stock'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/login'
    | '/select-context'
    | '/super-admin'
    | '/app/bills'
    | '/app/cashbook'
    | '/app/entry'
    | '/app/ledger'
    | '/app/masters'
    | '/app/pricing'
    | '/app/reports'
    | '/app/settings'
    | '/app/teep'
    | '/app/trial-balance'
    | '/super-admin/audit'
    | '/super-admin/leads'
    | '/app/'
    | '/super-admin/'
    | '/app/entry/challan'
    | '/app/entry/voucher'
    | '/app/masters/companies'
    | '/app/masters/expenses'
    | '/app/masters/items'
    | '/app/masters/parties'
    | '/app/stock/sale'
    | '/app/stock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  SelectContextRoute: typeof SelectContextRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-context': {
      id: '/select-context'
      path: '/select-context'
      fullPath: '/select-context'
      preLoaderRoute: typeof SelectContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/super-admin/leads': {
      id: '/super-admin/leads'
      path: '/leads'
      fullPath: '/super-admin/leads'
      preLoaderRoute: typeof SuperAdminLeadsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/audit': {
      id: '/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof SuperAdminAuditRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/app/trial-balance': {
      id: '/app/trial-balance'
      path: '/trial-balance'
      fullPath: '/app/trial-balance'
      preLoaderRoute: typeof AppTrialBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teep': {
      id: '/app/teep'
      path: '/teep'
      fullPath: '/app/teep'
      preLoaderRoute: typeof AppTeepRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pricing': {
      id: '/app/pricing'
      path: '/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masters': {
      id: '/app/masters'
      path: '/masters'
      fullPath: '/app/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entry': {
      id: '/app/entry'
      path: '/entry'
      fullPath: '/app/entry'
      preLoaderRoute: typeof AppEntryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cashbook': {
      id: '/app/cashbook'
      path: '/cashbook'
      fullPath: '/app/cashbook'
      preLoaderRoute: typeof AppCashbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock/': {
      id: '/app/stock/'
      path: '/stock'
      fullPath: '/app/stock/'
      preLoaderRoute: typeof AppStockIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock/sale': {
      id: '/app/stock/sale'
      path: '/stock/sale'
      fullPath: '/app/stock/sale'
      preLoaderRoute: typeof AppStockSaleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masters/parties': {
      id: '/app/masters/parties'
      path: '/parties'
      fullPath: '/app/masters/parties'
      preLoaderRoute: typeof AppMastersPartiesRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/app/masters/items': {
      id: '/app/masters/items'
      path: '/items'
      fullPath: '/app/masters/items'
      preLoaderRoute: typeof AppMastersItemsRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/app/masters/expenses': {
      id: '/app/masters/expenses'
      path: '/expenses'
      fullPath: '/app/masters/expenses'
      preLoaderRoute: typeof AppMastersExpensesRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/app/masters/companies': {
      id: '/app/masters/companies'
      path: '/companies'
      fullPath: '/app/masters/companies'
      preLoaderRoute: typeof AppMastersCompaniesRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/app/entry/voucher': {
      id: '/app/entry/voucher'
      path: '/voucher'
      fullPath: '/app/entry/voucher'
      preLoaderRoute: typeof AppEntryVoucherRouteImport
      parentRoute: typeof AppEntryRoute
    }
    '/app/entry/challan': {
      id: '/app/entry/challan'
      path: '/challan'
      fullPath: '/app/entry/challan'
      preLoaderRoute: typeof AppEntryChallanRouteImport
      parentRoute: typeof AppEntryRoute
    }
  }
}

interface AppEntryRouteChildren {
  AppEntryChallanRoute: typeof AppEntryChallanRoute
  AppEntryVoucherRoute: typeof AppEntryVoucherRoute
}

const AppEntryRouteChildren: AppEntryRouteChildren = {
  AppEntryChallanRoute: AppEntryChallanRoute,
  AppEntryVoucherRoute: AppEntryVoucherRoute,
}

const AppEntryRouteWithChildren = AppEntryRoute._addFileChildren(
  AppEntryRouteChildren,
)

interface AppMastersRouteChildren {
  AppMastersCompaniesRoute: typeof AppMastersCompaniesRoute
  AppMastersExpensesRoute: typeof AppMastersExpensesRoute
  AppMastersItemsRoute: typeof AppMastersItemsRoute
  AppMastersPartiesRoute: typeof AppMastersPartiesRoute
}

const AppMastersRouteChildren: AppMastersRouteChildren = {
  AppMastersCompaniesRoute: AppMastersCompaniesRoute,
  AppMastersExpensesRoute: AppMastersExpensesRoute,
  AppMastersItemsRoute: AppMastersItemsRoute,
  AppMastersPartiesRoute: AppMastersPartiesRoute,
}

const AppMastersRouteWithChildren = AppMastersRoute._addFileChildren(
  AppMastersRouteChildren,
)

interface AppRouteChildren {
  AppBillsRoute: typeof AppBillsRoute
  AppCashbookRoute: typeof AppCashbookRoute
  AppEntryRoute: typeof AppEntryRouteWithChildren
  AppLedgerRoute: typeof AppLedgerRoute
  AppMastersRoute: typeof AppMastersRouteWithChildren
  AppPricingRoute: typeof AppPricingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeepRoute: typeof AppTeepRoute
  AppTrialBalanceRoute: typeof AppTrialBalanceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppStockSaleRoute: typeof AppStockSaleRoute
  AppStockIndexRoute: typeof AppStockIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsRoute: AppBillsRoute,
  AppCashbookRoute: AppCashbookRoute,
  AppEntryRoute: AppEntryRouteWithChildren,
  AppLedgerRoute: AppLedgerRoute,
  AppMastersRoute: AppMastersRouteWithChildren,
  AppPricingRoute: AppPricingRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeepRoute: AppTeepRoute,
  AppTrialBalanceRoute: AppTrialBalanceRoute,
  AppIndexRoute: AppIndexRoute,
  AppStockSaleRoute: AppStockSaleRoute,
  AppStockIndexRoute: AppStockIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminAuditRoute: typeof SuperAdminAuditRoute
  SuperAdminLeadsRoute: typeof SuperAdminLeadsRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAuditRoute: SuperAdminAuditRoute,
  SuperAdminLeadsRoute: SuperAdminLeadsRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  SelectContextRoute: SelectContextRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
