/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectContextRouteImport } from './routes/select-context'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMastersRouteImport } from './routes/app.masters'
import { Route as AppMastersPartiesRouteImport } from './routes/app.masters.parties'
import { Route as AppMastersItemsRouteImport } from './routes/app.masters.items'
import { Route as AppMastersExpensesRouteImport } from './routes/app.masters.expenses'

const SelectContextRoute = SelectContextRouteImport.update({
  id: '/select-context',
  path: '/select-context',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersPartiesRoute = AppMastersPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppMastersItemsRoute = AppMastersItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppMastersRoute,
} as any)
const AppMastersExpensesRoute = AppMastersExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppMastersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select-context': typeof SelectContextRoute
  '/app/masters': typeof AppMastersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/masters/expenses': typeof AppMastersExpensesRoute
  '/app/masters/items': typeof AppMastersItemsRoute
  '/app/masters/parties': typeof AppMastersPartiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-context': typeof SelectContextRoute
  '/app/masters': typeof AppMastersRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/masters/expenses': typeof AppMastersExpensesRoute
  '/app/masters/items': typeof AppMastersItemsRoute
  '/app/masters/parties': typeof AppMastersPartiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select-context': typeof SelectContextRoute
  '/app/masters': typeof AppMastersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/masters/expenses': typeof AppMastersExpensesRoute
  '/app/masters/items': typeof AppMastersItemsRoute
  '/app/masters/parties': typeof AppMastersPartiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/select-context'
    | '/app/masters'
    | '/app/'
    | '/app/masters/expenses'
    | '/app/masters/items'
    | '/app/masters/parties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/select-context'
    | '/app/masters'
    | '/app'
    | '/app/masters/expenses'
    | '/app/masters/items'
    | '/app/masters/parties'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/select-context'
    | '/app/masters'
    | '/app/'
    | '/app/masters/expenses'
    | '/app/masters/items'
    | '/app/masters/parties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectContextRoute: typeof SelectContextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-context': {
      id: '/select-context'
      path: '/select-context'
      fullPath: '/select-context'
      preLoaderRoute: typeof SelectContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masters': {
      id: '/app/masters'
      path: '/masters'
      fullPath: '/app/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/masters/parties': {
      id: '/app/masters/parties'
      path: '/parties'
      fullPath: '/app/masters/parties'
      preLoaderRoute: typeof AppMastersPartiesRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/app/masters/items': {
      id: '/app/masters/items'
      path: '/items'
      fullPath: '/app/masters/items'
      preLoaderRoute: typeof AppMastersItemsRouteImport
      parentRoute: typeof AppMastersRoute
    }
    '/app/masters/expenses': {
      id: '/app/masters/expenses'
      path: '/expenses'
      fullPath: '/app/masters/expenses'
      preLoaderRoute: typeof AppMastersExpensesRouteImport
      parentRoute: typeof AppMastersRoute
    }
  }
}

interface AppMastersRouteChildren {
  AppMastersExpensesRoute: typeof AppMastersExpensesRoute
  AppMastersItemsRoute: typeof AppMastersItemsRoute
  AppMastersPartiesRoute: typeof AppMastersPartiesRoute
}

const AppMastersRouteChildren: AppMastersRouteChildren = {
  AppMastersExpensesRoute: AppMastersExpensesRoute,
  AppMastersItemsRoute: AppMastersItemsRoute,
  AppMastersPartiesRoute: AppMastersPartiesRoute,
}

const AppMastersRouteWithChildren = AppMastersRoute._addFileChildren(
  AppMastersRouteChildren,
)

interface AppRouteChildren {
  AppMastersRoute: typeof AppMastersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMastersRoute: AppMastersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectContextRoute: SelectContextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
